- trigger:
  - platform: state
    entity_id: binary_sensor.virtual_living_room_ms
    to: 'on'
  action:
  - event: living_room_occupied

- trigger:
  - platform: event
    event_type: living_room_occupied
  condition:
  - condition: state
    entity_id: light.virtual_daylight
    state: 'off'
  action:
  - service: light.turn_on
    target:
      entity_id: light.virtual_living_room_b

- trigger:
  - platform: state
    entity_id: binary_sensor.virtual_garage_ms
    to: 'on'
  action:
  - event: garage_occupied

- trigger:
  - platform: event
    event_type: garage_occupied
  action:
  - service: light.turn_on
    target:
      entity_id: light.virtual_living_room_b

- trigger:
  - platform: event
    event_type: kitchen_occupied
  action:
  - service: light.turn_on
    target:
      entity_id: light.virtual_kitchen_b

- trigger:
  - platform: state
    entity_id: binary_sensor.virtual_bedroom_ms
    to: 'on'
  action:
  - event: bedroom_occupied