default_config:

# https://github.com/twrecked/hass-virtual
virtual:

switch:
  - platform: virtual
    name: Switch 1
  - platform: virtual
    name: Switch 2

light:
  - platform: virtual
    name: 'Light 1'

automation: !include automations.yaml
