(load "/usr/share/scone/scone-start.lisp")
(load "scone-knowledge.d/01-general.lisp")
(load "scone-knowledge.d/02-statuses.lisp")
(load "scone-knowledge.d/03-events.lisp")
(load "scone-knowledge.d/04-rules.lisp")